version: '3'
services:
    web:
        build:
            context: .
            dockerfile: Dockerfile.dev
        ports:
            - '4000:3000'
        volumes:
            - /app/node_modules
            - .:/app
